# Generated by Django 3.0.8 on 2020-07-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200731_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFirstName', models.CharField(max_length=25)),
                ('customerLastName', models.CharField(max_length=25)),
                ('customerEmailAddress', models.CharField(max_length=150)),
                ('customerAddress', models.CharField(max_length=500)),
                ('customerCity', models.CharField(max_length=50)),
                ('customerPostalCode', models.IntegerField()),
                ('customerPhoneNumber', models.IntegerField()),
                ('publishData', models.DateTimeField(auto_now=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
