# Generated by Django 3.0.8 on 2020-08-01 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200801_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='publishData',
        ),
        migrations.AddField(
            model_name='order',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
