# Generated by Django 3.0.8 on 2020-08-01 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200801_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 13, 54, 54, 877257)),
        ),
    ]
